site_name: iNeko
site_description: 'Cats Never Wrong!'
site_author: 'iNeko Team'
site_url: 'https://ineko.cn'


# Copyright
copyright: 'Copyright &copy; 2018 - 2019 iNeko Team'

# Configuration
theme:
  name: 'material'

# Contents
pages:
  - Getting Started: index.md
  - Introduction:
    - 关于我们: introduction/about.md
    - 更新日志: introduction/log.md
    - 数据库结构: introduction/database.md
    - 目录树: introduction/tree.md
  - API:
    - API概览: api/introduction.md
    - 调用方式:
      - 请求结构: api/method/request.md
      - 返回结果: api/method/response.md
    - 版本更迭: api/history.md

# Search
extra:
  search:
    language: 'jp'